/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package junio;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Generos;

/**
 *
 * @author Antonio Miranda
 */
public class NewJDialog extends javax.swing.JDialog {
    Generos generos = new Generos();
    Font fuente = new Font("Area",Font.ITALIC,16);
    ImageIcon imagenSubir = new ImageIcon(getClass().getResource("/imagenes/arrow-up.png"));
    ImageIcon imagenBajar = new ImageIcon(getClass().getResource("/imagenes/arrow-down.png"));
    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        areaGeneros.setText(generos.devolucionGeneros());
        areaGeneros.setFont(fuente);
        areaGeneros.setForeground(Color.blue);
        botonSubir.setIcon(imagenSubir);
        botonBajar.setIcon(imagenBajar);
        System.out.println("Artelo");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaGeneros = new javax.swing.JTextArea();
        botonSubir = new javax.swing.JButton();
        botonBajar = new javax.swing.JButton();
        campoNumeroMover = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        areaGeneros.setColumns(20);
        areaGeneros.setRows(5);
        jScrollPane1.setViewportView(areaGeneros);

        botonSubir.setText(" ");
        botonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirActionPerformed(evt);
            }
        });

        botonBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduzca cual mover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBajar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(campoNumeroMover, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(campoNumeroMover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBajar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirActionPerformed
        int posS=0; 
        //Control de excepciones para controlar el error al introducir un valor que no se puede pasar a int
        try{
            posS=Integer.valueOf(campoNumeroMover.getText());
        }catch(NumberFormatException eConversionSubir){
            JOptionPane.showMessageDialog(null, "Introduzca un número", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        /*Otro control de excep. para controlar el error de los vectores al intentar mover el contenido de una posicón
        a otra posición que no exista en dicho vector*/
        try{
            /*En este bloque de sentencias usamos el método isPos() para saber si la posición es correcta, en ese caso
            hacemos una llamada al método mover() para que intercambie los contenidos de los elementos del vector
            para luego mostrarlos por pantalla en la aplicación mediante el método devolucionGeneros()*/
            if(generos.isPos(posS)){
            generos.mover(posS,posS-1);
            areaGeneros.setText(generos.devolucionGeneros());
            }else
            //Si la posición es incorrecta la aplicación pasa por else, mostrando un mensaje de error en una ventana emergente   
            JOptionPane.showMessageDialog(null, "Posición incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
        }catch(ArrayIndexOutOfBoundsException eArray2){
            JOptionPane.showMessageDialog(null, "Posición incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_botonSubirActionPerformed

    private void botonBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajarActionPerformed
        int posB=0;
        try{
            posB=Integer.valueOf(campoNumeroMover.getText());
        }catch(NumberFormatException eConversionBajar){
            JOptionPane.showMessageDialog(null, "Introduzca un número", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        try{
          if(generos.isPos(posB)){
        generos.mover(posB,posB+1);
        areaGeneros.setText(generos.devolucionGeneros());
        }else
            JOptionPane.showMessageDialog(null, "Posición incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);  
        }catch(ArrayIndexOutOfBoundsException eArray1){
            JOptionPane.showMessageDialog(null, "Posición incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_botonBajarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaGeneros;
    private javax.swing.JButton botonBajar;
    private javax.swing.JButton botonSubir;
    private javax.swing.JTextField campoNumeroMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
